__version__: 1.3.1
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  is_check_shapes: true
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: HorizontalFlip
    always_apply: false
    p: 0.5
  - __class_fullname__: VerticalFlip
    always_apply: false
    p: 0.5
  - __class_fullname__: HueSaturationValue
    always_apply: false
    hue_shift_limit:
    - -20
    - 20
    p: 0.5
    sat_shift_limit:
    - -30
    - 30
    val_shift_limit:
    - -20
    - 20
  - __class_fullname__: RandomBrightnessContrast
    always_apply: false
    brightness_by_max: true
    brightness_limit:
    - -0.2
    - 0.2
    contrast_limit:
    - -0.2
    - 0.2
    p: 0.5
  - __class_fullname__: ShiftScaleRotate
    always_apply: false
    border_mode: 4
    interpolation: 1
    mask_value: null
    p: 0.5
    rotate_limit:
    - -45
    - 45
    rotate_method: largest_box
    scale_limit:
    - -0.09999999999999998
    - 0.10000000000000009
    shift_limit_x:
    - -0.0625
    - 0.0625
    shift_limit_y:
    - -0.0625
    - 0.0625
    value: null
  - __class_fullname__: GaussianBlur
    always_apply: false
    blur_limit:
    - 3
    - 7
    p: 0.5
    sigma_limit:
    - 0
    - 0